log_level: DEBUG
dataset_path: ../datasets/
vector_store:
  type: milvus
  url: "http://localhost:19530"
  collection_name: knowledge_base
  reset_collection: true
  enable_full_text_search: true
chunk_size: 1000
chunk_overlap: 200
